# When the workflow should run
on:
push:
 branches: ["main"]
pull_request:
branches: ["main"]

# What jobs to run
jobs:
build:
runs-on:ubuntu-latest# Environment to run in

steps:
# Step 1: Checkout the code
-name:Checkoutrepository
uses:actions/checkout@v4

# Step 2: Run a simple command
-name:Displaymessage
run:echo"GitHub Actions workflow is running successfully!"